### ISSUE TITLE
Tues morning checklist

### ISSUE THREAD

**Issue by stevenjackson** [stevenjackson/devour-the-cloud-instructor#2]
- [x] Latest AMIs public
- [x] AMI IDs handy
- [x] Branches rebased on master
- [x] Logged into AWS console
- [x] Instances based on latest AMI
- [x] Instances running
- [x] load test baseline
- [ ] Slides loaded
- [ ] Projector check
- [ ] Slack (only codemash)
